# Generated by Django 3.2.8 on 2022-06-10 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confidentialApp', '0002_saletext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('confidential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='confidentialApp.confidential')),
            ],
            options={
                'verbose_name_plural': 'Инструкции',
            },
            bases=('confidentialApp.confidential',),
        ),
    ]
