# Generated by Django 3.2.8 on 2022-09-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialistApp', '0011_alter_specialist_days_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актививация видов деятельности'),
        ),
    ]
